#!/bin/sh

git_user=rflowers

if [ "$#" -lt 2 ]; then
	echo "Usage: $(basename $0) GITUSER REPO [NUMBER]"
else
	git_user="$1"
	base_repo="$2"
fi

if [ -n "$2" ]; then
	postfix="$2"
fi

repo=$git_user/${base_repo}${postfix}

ssh ece2524git@ece2524.ece.vt.edu fork $base_repo $repo
git clone ece2524git@ece2524.ece.vt.edu:$repo
