#!/bin/sh

git_user=rflowers

if [ -z "$1" ]; then
     	base_repo="midterm/practice"
else
	base_repo="$1"
fi

if [ -n "$2" ]; then
	postfix="$2"
fi

repo=$git_user/${base_repo}${postfix}

ssh ece2524git@ece2524.ece.vt.edu fork $base_repo $repo
git clone ece2524git@ece2524.ece.vt.edu:$repo
